app = "moto"
primary_region = "gru"
kill_signal = "SIGINT"
kill_timeout = 5

[build]
  dockerfile = "Dockerfile"

[env]
  PORT = "8080"
  HOST = "0.0.0.0"
  ENVIRONMENT = "production"
  FORCE_HTTPS = "true"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

  [[http_service.checks]]
    grace_period = "30s"
    interval = "60s"
    method = "GET"
    path = "/health"
    timeout = "10s"

[vm]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 512# Trigger rebuild Mon Jul 28 04:39:53 PM UTC 2025
